### ISSUE TITLE
Missing commits!

### ISSUE THREAD

**Issue by ProfPollati** [Bloomfield-FA15-CAT238/Assignment12-ValencioWilliams#1]
As stated in the instructions

> - You must check it in at the same points that you see the ":white_check_mark: [Git commit]()" messages to receive full credit!

That cost you about 60 points! It only dropped your grade by 2.5 points. If you really want to start again, and create a new repo, and go through committing every time, then I will revise the grade accordingly.

**Comment by resident5** [comment]
I never understood that part of the instructions. What did you mean check
it in at the same parts I see the git commit messages? When I click on the
link in the in that was there it just refreshed the page. Am I missing
something?

**Comment by resident5** [comment]
Nevermind I see them...

**Comment by resident5** [comment]
I believe I did it right this time in the new Assignment 12 redo repo

**Comment by ProfPollati** [comment]
Okay, I updated your grade...
